/*
 * generated by Xtext
 */
package jp.ac.kyushu.ui.contentassist

import jp.ac.kyushu.ui.contentassist.AbstractArgyleProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ArgyleProposalProvider extends AbstractArgyleProposalProvider {
}
