/*
 * generated by Xtext
 */
package jp.ac.kyushu.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ArgyleUiModule extends jp.ac.kyushu.ui.AbstractArgyleUiModule {
	public ArgyleUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
