/*
 * generated by Xtext
 */
package jp.ac.kyushu;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ArgyleRuntimeModule extends jp.ac.kyushu.AbstractArgyleRuntimeModule {

}

