/*
* generated by Xtext
*/
package jp.ac.kyushu;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ArgyleStandaloneSetup extends ArgyleStandaloneSetupGenerated{

	public static void doSetup() {
		new ArgyleStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

